using UnityEngine;
using System;
using System.IO;
using UnityEngine.SceneManagement;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.AddressableAssets;
using UnityEngine.ResourceManagement.AsyncOperations;

// every manager will derive from the Singleton class - this makes sure there is only one single manager of this type in the whole app.
public class GameManager : Singleton<GameManager>
{
    // this is how to define an event - how the manager communicates with the rest of the app components
    public event Action<LevelData> OnDataLoaded;
    public event Action<LevelData> OnLevelRestartedEvent;

    [SerializeField] private LevelData _levelData;
    [SerializeField] private string _levelJson;
    [SerializeField] private TextAsset[] _levelJsonFiles;
    [SerializeField] private TextAsset _classicLevelJsonFile;
    [Min(1)]
    [SerializeField] private int startLevelIndex = 1;

    [Header("Addressables Levels")]
    [SerializeField] private bool useAddressablesForLevels;
    [SerializeField] private string adventureLevelsLabel;
    [SerializeField] private string classicLevelsLabel;

    [Header("Scene Navigation")]
    [SerializeField] private int adventureLobbySceneBuildIndex = 0;
    [SerializeField] private int classicGameSceneBuildIndex = 0;

    // Levels 1-3 are the only ones with hand-curated content (Assets/Levels/Level1-3.json,
    // still Inspector/Addressables-loaded below); every level from 4 on is generated by
    // AdventureLevelFactory, so Adventure never runs out of levels. 0-based index, so this is a
    // count of static levels, not a level number.
    private const int StaticAdventureLevelCount = 3;

    public enum GameMode
    {
        Adventure = 0,
        Classic = 1
    }

    private const string SelectedGameModeKey = "selected_game_mode";

    public GameMode CurrentGameMode
    {
        get
        {
            return (GameMode)PlayerPrefs.GetInt(SelectedGameModeKey, (int)GameMode.Adventure);
        }
    }

    public LevelData CurrentLevelData => AppManager.instance != null ? AppManager.instance.CurrentLevelData : null;
    
    // Game Mode Management
    private IGameMode currentGameModeInstance;
    
    public IGameMode CurrentGameModeInstance
    {
        get { return currentGameModeInstance; }
    }
    
    private int lastLoadedSceneHandle = -1;

    private readonly List<TextAsset> addressableAdventureLevels = new List<TextAsset>();
    private TextAsset addressableClassicLevel;
    private bool addressablesAdventureLoaded;
    private bool addressablesClassicLoaded;
    private bool addressablesAdventureLoading;
    private bool addressablesClassicLoading;
    private AsyncOperationHandle<IList<TextAsset>> adventureHandle;
    private AsyncOperationHandle<IList<TextAsset>> classicHandle;

    [ContextMenu("Debug/Force Reload Addressables Levels")]
    public void DebugForceReloadAddressablesLevels()
    {
        if (adventureHandle.IsValid())
            Addressables.Release(adventureHandle);
        if (classicHandle.IsValid())
            Addressables.Release(classicHandle);

        addressableAdventureLevels.Clear();
        addressableClassicLevel = null;
        addressablesAdventureLoaded = false;
        addressablesClassicLoaded = false;
        addressablesAdventureLoading = false;
        addressablesClassicLoading = false;

        // Debug.Log("GameManager -> Forced reload of Addressables levels cache. Reload the scene to re-fetch assets.");
    }

    [ContextMenu("Debug/Force Reload Addressables Levels And Reload Scene")]
    public void DebugForceReloadAddressablesLevelsAndReloadScene()
    {
        DebugForceReloadAddressablesLevels();
        ReloadCurrentScene();
    }

    private void OnEnable()
    {
        SceneManager.sceneLoaded += HandleSceneLoaded;

    }

    private void OnDisable()
    {
        SceneManager.sceneLoaded -= HandleSceneLoaded;

    }

    private void OnDestroy()
    {
        if (adventureHandle.IsValid())
            Addressables.Release(adventureHandle);
        if (classicHandle.IsValid())
            Addressables.Release(classicHandle);
    }

    //private void Start()
    //{
    //    if (CurrentLevelData == null)
    //        HandleSceneLoaded(SceneManager.GetActiveScene(), LoadSceneMode.Single);
    //}
    public void DebugResetProgressToLevel1AndReloadScene()
    {


        var scene = SceneManager.GetActiveScene();
        SceneManager.LoadScene(scene.buildIndex);
    }

    public void SetLevelCompleted(int levelIndex)
    {
        var playerProgress = PlayerManeger.instance.PlayerProgress;
        if (playerProgress == null)
            PlayerManeger.instance.LoadPlayerProgress();

        if (levelIndex + 1 > playerProgress.HighestUnlockedLevel)
        {
            playerProgress.HighestUnlockedLevel = levelIndex + 1;
            PlayerManeger.instance.SavePlayerProgress();
        }
        else
        {
            //Debug.Log($"Level {levelIndex} completed but highestUnlockedLevel already {PlayerManeger.instance.PlayerProgress.HighestUnlockedLevel}, not updating.");
        }
    }

    public void ReloadCurrentScene()
    {
        var scene = SceneManager.GetActiveScene();
        SceneManager.LoadScene(scene.buildIndex);
    }

    private void HandleSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        // Debug.Log($"GameManager -> HandleSceneLoaded: scene='{scene.name}' (buildIndex={scene.buildIndex}), CurrentGameMode={CurrentGameMode}");
        if (scene.handle == lastLoadedSceneHandle)
            return;

        lastLoadedSceneHandle = scene.handle;

        // Initialize the appropriate game mode
        InitializeGameMode();

        // Reset current score whenever the main gameplay scene loads, while keeping MaxScore/high score.
        if (scene.buildIndex == classicGameSceneBuildIndex && ScoreManager.instance != null)
        {
            ScoreManager.instance.ResetScore();
        }

        if (CurrentGameMode == GameMode.Classic)
        {
            // Classic mode: always load the single classic JSON/config for the shared GameScene
            if (useAddressablesForLevels)
            {
                StartCoroutine(LoadClassicFromAddressablesThenInvoke(scene));
                return;
            }

            if (_classicLevelJsonFile != null)
            {
                // Debug.Log($"GameManager -> Classic mode: loading classic json '{_classicLevelJsonFile.name}' for scene '{scene.name}'.");
                LoadLevelFromJson(_classicLevelJsonFile.text);
                return;
            }

            if (!string.IsNullOrEmpty(_levelJson))
            {
                // Debug.Log($"GameManager -> Classic mode: loading classic json from _levelJson for scene '{scene.name}'.");
                LoadLevelFromJson(_levelJson);
                return;
            }

            // Debug.LogError($"GameManager -> Classic mode selected but no classic json is assigned. Assign _classicLevelJsonFile in the persistent GameManager (DontDestroyOnLoad).");
            return;
        }

        // Adventure mode: single shared GameScene, level is chosen purely by player progress (0-based HighestUnlockedLevel)
        int index = Mathf.Max(0, PlayerManeger.instance.PlayerProgress.HighestUnlockedLevel);

        if (useAddressablesForLevels)
        {
            StartCoroutine(LoadAdventureFromAddressablesThenLoadIndex(index));
            return;
        }

        if (_levelJsonFiles != null && _levelJsonFiles.Length > 0)
            LoadLevel(index);
        else
            LoadLevelFromJson(_levelJson);
    }

    public void InvokeOnLevelRestartedEvent ()
    {
        OnLevelRestartedEvent?.Invoke(CurrentLevelData);
    }

    private IEnumerator LoadAdventureFromAddressablesThenLoadIndex(int index)
    {
        if (addressablesAdventureLoaded)
        {
            LoadAdventureLevelByIndex(index);
            yield break;
        }

        if (addressablesAdventureLoading)
        {
            while (addressablesAdventureLoading)
                yield return null;

            if (addressablesAdventureLoaded)
                LoadAdventureLevelByIndex(index);
            yield break;
        }

        addressablesAdventureLoading = true;

        if (string.IsNullOrEmpty(adventureLevelsLabel))
        {
            Debug.LogError("GameManager -> useAddressablesForLevels is enabled but adventureLevelsLabel is empty. Falling back to inspector levels.");
            addressablesAdventureLoading = false;
            if (_levelJsonFiles != null && _levelJsonFiles.Length > 0)
                LoadLevel(index);
            else
                LoadLevelFromJson(_levelJson);
            yield break;
        }

        adventureHandle = Addressables.LoadAssetsAsync<TextAsset>(adventureLevelsLabel, null);
        yield return adventureHandle;

        addressableAdventureLevels.Clear();
        if (adventureHandle.Status == AsyncOperationStatus.Succeeded && adventureHandle.Result != null)
        {
            foreach (var ta in adventureHandle.Result)
            {
                if (ta != null)
                    addressableAdventureLevels.Add(ta);
            }

            addressableAdventureLevels.Sort((a, b) => GetLevelNumberSafe(a).CompareTo(GetLevelNumberSafe(b)));
            addressablesAdventureLoaded = addressableAdventureLevels.Count > 0;
        }
        else
        {
            Debug.LogError($"GameManager -> Failed to load adventure levels via Addressables label '{adventureLevelsLabel}'. Falling back to inspector levels.");
            addressablesAdventureLoaded = false;
        }

        addressablesAdventureLoading = false;

        if (addressablesAdventureLoaded)
            LoadAdventureLevelByIndex(index);
        else if (_levelJsonFiles != null && _levelJsonFiles.Length > 0)
            LoadLevel(index);
        else
            LoadLevelFromJson(_levelJson);
    }

    private void LoadAdventureLevelByIndex(int index)
    {
        if (index < 0)
            return;

        if (index >= StaticAdventureLevelCount || index >= addressableAdventureLevels.Count)
        {
            LoadGeneratedAdventureLevel(index);
            return;
        }

        var ta = addressableAdventureLevels[index];
        if (ta == null)
            return;

        LoadLevelFromJson(ta.text);
    }

    private IEnumerator LoadClassicFromAddressablesThenInvoke(Scene scene)
    {
        if (addressablesClassicLoaded)
        {
            if (addressableClassicLevel != null)
            {
                Debug.Log($"GameManager -> Classic mode: loading classic json '{addressableClassicLevel.name}' via Addressables for scene '{scene.name}'.");
                LoadLevelFromJson(addressableClassicLevel.text);
            }
            yield break;
        }

        if (addressablesClassicLoading)
        {
            while (addressablesClassicLoading)
                yield return null;

            if (addressablesClassicLoaded && addressableClassicLevel != null)
            {
                Debug.Log($"GameManager -> Classic mode: loading classic json '{addressableClassicLevel.name}' via Addressables for scene '{scene.name}'.");
                LoadLevelFromJson(addressableClassicLevel.text);
            }
            yield break;
        }

        addressablesClassicLoading = true;

        if (string.IsNullOrEmpty(classicLevelsLabel))
        {
            Debug.LogError("GameManager -> useAddressablesForLevels is enabled but classicLevelsLabel is empty. Falling back to inspector classic json.");
            addressablesClassicLoading = false;

            if (_classicLevelJsonFile != null)
                LoadLevelFromJson(_classicLevelJsonFile.text);
            else
                LoadLevelFromJson(_levelJson);
            yield break;
        }

        classicHandle = Addressables.LoadAssetsAsync<TextAsset>(classicLevelsLabel, null);
        yield return classicHandle;

        addressableClassicLevel = null;
        if (classicHandle.Status == AsyncOperationStatus.Succeeded && classicHandle.Result != null)
        {
            for (int i = 0; i < classicHandle.Result.Count; i++)
            {
                var ta = classicHandle.Result[i];
                if (ta == null)
                    continue;

                addressableClassicLevel = ta;
                break;
            }

            addressablesClassicLoaded = addressableClassicLevel != null;
        }
        else
        {
            Debug.LogError($"GameManager -> Failed to load classic levels via Addressables label '{classicLevelsLabel}'. Falling back to inspector classic json.");
            addressablesClassicLoaded = false;
        }

        addressablesClassicLoading = false;

        if (addressablesClassicLoaded && addressableClassicLevel != null)
        {
            Debug.Log($"GameManager -> Classic mode: loading classic json '{addressableClassicLevel.name}' via Addressables for scene '{scene.name}'.");
            LoadLevelFromJson(addressableClassicLevel.text);
        }
        else if (_classicLevelJsonFile != null)
        {
            LoadLevelFromJson(_classicLevelJsonFile.text);
        }
        else
        {
            LoadLevelFromJson(_levelJson);
        }
    }

    private int GetLevelNumberSafe(TextAsset ta)
    {
        if (ta == null)
            return int.MaxValue;

        try
        {
            var data = JsonUtility.FromJson<LevelData>(ta.text);
            if (data != null && data.Level > 0)
            {
                if (data.Level==1)
                {
                    Debug.Log("masheho");
                }
                return data.Level;

            }
        }
        catch
        {
        }

        return int.MaxValue;
    }

    public void InitData()
    {
        // take LevelData and convert it to json string

        var json = JsonUtility.ToJson(_levelData);
        Debug.Log(json);
		if (_levelJsonFiles != null && _levelJsonFiles.Length > 0)
            LoadLevel(Mathf.Max(0, startLevelIndex - 1));
        else
            LoadLevelFromJson(_levelJson);
    }

    [ContextMenu("Load Selected Level Index")]
    public void LoadSelectedLevelIndex()
    {
        LoadLevel(Mathf.Max(0, startLevelIndex - 1));
    }

    public void LoadLevel(int index)
    {
        if (index < 0)
            return;

        if (index >= StaticAdventureLevelCount)
        {
            LoadGeneratedAdventureLevel(index);
            return;
        }

        if (_levelJsonFiles == null || index >= _levelJsonFiles.Length)
            return;

        var file = _levelJsonFiles[index];
        if (file == null)
            return;

        LoadLevelFromJson(file.text);
    }

    // Adventure has no level ceiling: past the 3 hand-curated tutorial levels, every level is
    // generated on demand so play never dead-ends. Levels 4-35 used to be pre-baked JSON files;
    // those (and their Addressables entries) are gone now that every level 4+ is generated the
    // same way, so this always wins over the static array/Addressables lookups above.
    private void LoadGeneratedAdventureLevel(int index)
    {
        var generated = AdventureLevelFactory.Generate(index + 1);
        LoadLevelFromJson(JsonUtility.ToJson(generated));
    }

    private void LoadLevelFromJson(string json)
    {
        if (string.IsNullOrEmpty(json))
            return;

        var levelData = JsonUtility.FromJson<LevelData>(json);
        if (levelData == null)
            return;

      

        InvokeOnDataLoaded(levelData);
    }

    public void InvokeOnDataLoaded(LevelData levelData)
    {
        OnDataLoaded?.Invoke(levelData);
    }

    #region Game Mode Management
    
    /// <summary>
    /// Initialize the appropriate game mode based on CurrentGameMode
    /// </summary>
    private void InitializeGameMode()
    {
        // Cleanup previous game mode if exists
        if (currentGameModeInstance != null)
        {
            currentGameModeInstance.Cleanup();
            currentGameModeInstance = null;
        }
        
        // Create new game mode instance
        switch (CurrentGameMode)
        {
            case GameMode.Classic:
                currentGameModeInstance = new ClassicGameMode();
                break;
            case GameMode.Adventure:
                currentGameModeInstance = new AdventureGameMode();
                break;
            default:
                currentGameModeInstance = new AdventureGameMode(); // Default to Adventure
                break;
        }
        
        // Initialize the new game mode
        currentGameModeInstance.Initialize();
        
        Debug.Log($"[GameManager] Initialized {CurrentGameMode} game mode");
    }
    
    /// <summary>
    /// Switch to a specific game mode
    /// </summary>
    public void SwitchToGameMode(GameMode gameMode)
    {
        PlayerPrefs.SetInt(SelectedGameModeKey, (int)gameMode);
        PlayerPrefs.Save();
        
        Debug.Log($"[GameManager] Switching to {gameMode} mode");
        
        // Reinitialize with new game mode
        InitializeGameMode();
    }
    
    /// <summary>
    /// Forward shape placement to current game mode
    /// </summary>
    public void HandleShapePlaced(Shape shape)
    {
        if (currentGameModeInstance != null)
        {
            currentGameModeInstance.HandleShapePlaced(shape);
        }
    }
    
    /// <summary>
    /// Forward game over check to current game mode
    /// </summary>
    public void CheckGameOver()
    {
        if (currentGameModeInstance != null)
        {
            currentGameModeInstance.CheckGameOver();
        }
    }
    
    /// <summary>
    /// Reset current game mode
    /// </summary>
    public void ResetCurrentGameMode()
    {
        if (currentGameModeInstance != null)
        {
            currentGameModeInstance.Reset();
        }
    }
    
    #endregion
}